---
ID: "e86a40a7-0aed-4dcf-92cb-e502ebe74330"
Parent: "b0c012ca-b519-4073-96ac-fe1d2e243391"
Template: "93227c5d-4fef-474d-94c0-f252ec8e8219"
Path: /sitecore/layout/Layouts/HCA/Project
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170501T174713Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a2f87d6f-1487-40ab-b522-ba41278e639e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210122T150006Z
