//    Copyright 2020 EPAM Systems, Inc.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Rainbow JS CodeGeneration.
//     (https://github.com/asmagin/rainbow-js-codegeneration)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCA.Project.HCA.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Text;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Configuration;
    using Glass.Mapper.Sc.Fields;
    using Sitecore.Globalization;
    using Sitecore.Data;
    using Sitecore.Data.Items;

    using System.CodeDom.Compiler;
    using global::HCA.Foundation.GlassMapper.Models;


    /// <summary>
    /// ICart Interface
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Pages/Cart</para>
    /// <para>ID: d0466420-eeca-46a4-93b6-b17cc198e87b</para>
    /// </summary>
    [SitecoreType(TemplateId="d0466420-eeca-46a4-93b6-b17cc198e87b")]
    public partial interface ICart: IPage, IGlassBase
    {

    }


    /// <summary>
    /// Cart Class
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Pages/Cart</para>
    /// <para>ID: d0466420-eeca-46a4-93b6-b17cc198e87b</para>
    /// </summary>
    [SitecoreType(TemplateId="d0466420-eeca-46a4-93b6-b17cc198e87b")]
    public partial class Cart: GlassBase, ICart
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Project/HCA/Pages/Cart
        /// </summary>
        public const string TemplateId = "d0466420-eeca-46a4-93b6-b17cc198e87b";

    }


    /// <summary>
    /// ICategory Interface
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Pages/Category</para>
    /// <para>ID: 0cbbb134-4025-4a51-9b46-1ab7021ccb0f</para>
    /// </summary>
    [SitecoreType(TemplateId="0cbbb134-4025-4a51-9b46-1ab7021ccb0f")]
    public partial interface ICategory: IPage, IGlassBase
    {

    }


    /// <summary>
    /// Category Class
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Pages/Category</para>
    /// <para>ID: 0cbbb134-4025-4a51-9b46-1ab7021ccb0f</para>
    /// </summary>
    [SitecoreType(TemplateId="0cbbb134-4025-4a51-9b46-1ab7021ccb0f")]
    public partial class Category: GlassBase, ICategory
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Project/HCA/Pages/Category
        /// </summary>
        public const string TemplateId = "0cbbb134-4025-4a51-9b46-1ab7021ccb0f";

    }


    /// <summary>
    /// ICheckout Interface
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Pages/Checkout</para>
    /// <para>ID: d5440345-d25e-4a9b-b8e4-5c2aef3c9178</para>
    /// </summary>
    [SitecoreType(TemplateId="d5440345-d25e-4a9b-b8e4-5c2aef3c9178")]
    public partial interface ICheckout: IPage, IGlassBase
    {

    }


    /// <summary>
    /// Checkout Class
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Pages/Checkout</para>
    /// <para>ID: d5440345-d25e-4a9b-b8e4-5c2aef3c9178</para>
    /// </summary>
    [SitecoreType(TemplateId="d5440345-d25e-4a9b-b8e4-5c2aef3c9178")]
    public partial class Checkout: GlassBase, ICheckout
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Project/HCA/Pages/Checkout
        /// </summary>
        public const string TemplateId = "d5440345-d25e-4a9b-b8e4-5c2aef3c9178";

    }


    /// <summary>
    /// IDataFolder Interface
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Folders/Data Folder</para>
    /// <para>ID: 5c07e9e8-6ca9-43ad-9cec-2988a77f6d70</para>
    /// </summary>
    [SitecoreType(TemplateId="5c07e9e8-6ca9-43ad-9cec-2988a77f6d70")]
    public partial interface IDataFolder: IGlassBase
    {

    }


    /// <summary>
    /// DataFolder Class
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Folders/Data Folder</para>
    /// <para>ID: 5c07e9e8-6ca9-43ad-9cec-2988a77f6d70</para>
    /// </summary>
    [SitecoreType(TemplateId="5c07e9e8-6ca9-43ad-9cec-2988a77f6d70")]
    public partial class DataFolder: GlassBase, IDataFolder
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Project/HCA/Folders/Data Folder
        /// </summary>
        public const string TemplateId = "5c07e9e8-6ca9-43ad-9cec-2988a77f6d70";

    }


    /// <summary>
    /// IGridLayout Interface
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Scaffolding/Rendering Parameters/Grid Layout</para>
    /// <para>ID: 61ed6a03-bbdb-4937-87fa-db5c53fc870c</para>
    /// </summary>
    [SitecoreType(TemplateId="61ed6a03-bbdb-4937-87fa-db5c53fc870c")]
    public partial interface IGridLayout: IGlassBase
    {

        /// <summary>
        /// The First Column Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: a10a1cf0-25e7-4b9f-a9ac-6d40de3cbe88</para>
        /// </summary>
        [SitecoreField("First Column Class")]
        string FirstColumnClass {get; set;}

        /// <summary>
        /// The Second Column Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 525bb442-fc9e-49dd-b557-52b833f0855d</para>
        /// </summary>
        [SitecoreField("Second Column Class")]
        string SecondColumnClass {get; set;}

        /// <summary>
        /// The Third Column Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: bfed443f-3ac3-460d-be12-5759b8294233</para>
        /// </summary>
        [SitecoreField("Third Column Class")]
        string ThirdColumnClass {get; set;}

        /// <summary>
        /// The Wrapper Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: b4386ac8-1f1b-49f3-adcb-264f5f595e52</para>
        /// </summary>
        [SitecoreField("Wrapper Class")]
        string WrapperClass {get; set;}

    }


    /// <summary>
    /// GridLayout Class
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Scaffolding/Rendering Parameters/Grid Layout</para>
    /// <para>ID: 61ed6a03-bbdb-4937-87fa-db5c53fc870c</para>
    /// </summary>
    [SitecoreType(TemplateId="61ed6a03-bbdb-4937-87fa-db5c53fc870c")]
    public partial class GridLayout: GlassBase, IGridLayout
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Project/HCA/Scaffolding/Rendering Parameters/Grid Layout
        /// </summary>
        public const string TemplateId = "61ed6a03-bbdb-4937-87fa-db5c53fc870c";

        /// <summary>
        /// The First Column Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: a10a1cf0-25e7-4b9f-a9ac-6d40de3cbe88</para>
        /// </summary>
        [SitecoreField("First Column Class")]
        public virtual string FirstColumnClass {get; set;}
        public const string FirstColumnClassFieldId = "a10a1cf0-25e7-4b9f-a9ac-6d40de3cbe88";
        public const string FirstColumnClassFieldName = "First Column Class";

        /// <summary>
        /// The Second Column Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 525bb442-fc9e-49dd-b557-52b833f0855d</para>
        /// </summary>
        [SitecoreField("Second Column Class")]
        public virtual string SecondColumnClass {get; set;}
        public const string SecondColumnClassFieldId = "525bb442-fc9e-49dd-b557-52b833f0855d";
        public const string SecondColumnClassFieldName = "Second Column Class";

        /// <summary>
        /// The Third Column Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: bfed443f-3ac3-460d-be12-5759b8294233</para>
        /// </summary>
        [SitecoreField("Third Column Class")]
        public virtual string ThirdColumnClass {get; set;}
        public const string ThirdColumnClassFieldId = "bfed443f-3ac3-460d-be12-5759b8294233";
        public const string ThirdColumnClassFieldName = "Third Column Class";

        /// <summary>
        /// The Wrapper Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: b4386ac8-1f1b-49f3-adcb-264f5f595e52</para>
        /// </summary>
        [SitecoreField("Wrapper Class")]
        public virtual string WrapperClass {get; set;}
        public const string WrapperClassFieldId = "b4386ac8-1f1b-49f3-adcb-264f5f595e52";
        public const string WrapperClassFieldName = "Wrapper Class";

    }


    /// <summary>
    /// IHome Interface
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Pages/Home</para>
    /// <para>ID: 83883836-8f50-4bb8-bf62-369b7661e815</para>
    /// </summary>
    [SitecoreType(TemplateId="83883836-8f50-4bb8-bf62-369b7661e815")]
    public partial interface IHome: IPage, IGlassBase
    {

    }


    /// <summary>
    /// Home Class
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Pages/Home</para>
    /// <para>ID: 83883836-8f50-4bb8-bf62-369b7661e815</para>
    /// </summary>
    [SitecoreType(TemplateId="83883836-8f50-4bb8-bf62-369b7661e815")]
    public partial class Home: GlassBase, IHome
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Project/HCA/Pages/Home
        /// </summary>
        public const string TemplateId = "83883836-8f50-4bb8-bf62-369b7661e815";

    }


    /// <summary>
    /// IPage Interface
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Pages/Page</para>
    /// <para>ID: 9ca4a8c4-0295-49c1-a879-e008933d0a4f</para>
    /// </summary>
    [SitecoreType(TemplateId="9ca4a8c4-0295-49c1-a879-e008933d0a4f")]
    public partial interface IPage: IGlassBase
    {

    }


    /// <summary>
    /// Page Class
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Pages/Page</para>
    /// <para>ID: 9ca4a8c4-0295-49c1-a879-e008933d0a4f</para>
    /// </summary>
    [SitecoreType(TemplateId="9ca4a8c4-0295-49c1-a879-e008933d0a4f")]
    public partial class Page: GlassBase, IPage
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Project/HCA/Pages/Page
        /// </summary>
        public const string TemplateId = "9ca4a8c4-0295-49c1-a879-e008933d0a4f";

    }


    /// <summary>
    /// IProduct Interface
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Pages/Product</para>
    /// <para>ID: 1daeff25-b075-4c13-b41a-72b553b22542</para>
    /// </summary>
    [SitecoreType(TemplateId="1daeff25-b075-4c13-b41a-72b553b22542")]
    public partial interface IProduct: IPage, IGlassBase
    {

    }


    /// <summary>
    /// Product Class
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Pages/Product</para>
    /// <para>ID: 1daeff25-b075-4c13-b41a-72b553b22542</para>
    /// </summary>
    [SitecoreType(TemplateId="1daeff25-b075-4c13-b41a-72b553b22542")]
    public partial class Product: GlassBase, IProduct
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Project/HCA/Pages/Product
        /// </summary>
        public const string TemplateId = "1daeff25-b075-4c13-b41a-72b553b22542";

    }


    /// <summary>
    /// ISettingsFolder Interface
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Folders/Settings Folder</para>
    /// <para>ID: ff3f660a-3d15-4efc-9873-113aaf71b44e</para>
    /// </summary>
    [SitecoreType(TemplateId="ff3f660a-3d15-4efc-9873-113aaf71b44e")]
    public partial interface ISettingsFolder: IGlassBase
    {

    }


    /// <summary>
    /// SettingsFolder Class
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Folders/Settings Folder</para>
    /// <para>ID: ff3f660a-3d15-4efc-9873-113aaf71b44e</para>
    /// </summary>
    [SitecoreType(TemplateId="ff3f660a-3d15-4efc-9873-113aaf71b44e")]
    public partial class SettingsFolder: GlassBase, ISettingsFolder
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Project/HCA/Folders/Settings Folder
        /// </summary>
        public const string TemplateId = "ff3f660a-3d15-4efc-9873-113aaf71b44e";

    }


    /// <summary>
    /// IWishlistPage Interface
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Pages/Wishlist Page</para>
    /// <para>ID: e5e2329c-b05a-4e98-9430-018503c2699a</para>
    /// </summary>
    [SitecoreType(TemplateId="e5e2329c-b05a-4e98-9430-018503c2699a")]
    public partial interface IWishlistPage: IPage, IGlassBase
    {

    }


    /// <summary>
    /// WishlistPage Class
    /// <para>Path: /sitecore/templates/HCA/Project/HCA/Pages/Wishlist Page</para>
    /// <para>ID: e5e2329c-b05a-4e98-9430-018503c2699a</para>
    /// </summary>
    [SitecoreType(TemplateId="e5e2329c-b05a-4e98-9430-018503c2699a")]
    public partial class WishlistPage: GlassBase, IWishlistPage
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Project/HCA/Pages/Wishlist Page
        /// </summary>
        public const string TemplateId = "e5e2329c-b05a-4e98-9430-018503c2699a";

    }

}