---
ID: "5ea258fd-3d23-4361-9b5f-0bde61c1bbb3"
Parent: "169f36a3-309a-480b-82ca-5b40ae2e86c6"
Template: "6a553ec0-2ab9-49d6-be0e-a472e5e24213"
Path: /sitecore/templates/Commerce/Inventory/InventorySku/Commerce/StockOutThreshold
SharedFields:
- ID: "09e76fed-d919-4277-b6bf-748628dfd8ed"
  Hint: Managed by External Commerce System
  Value: 1
- ID: "21828437-ea4b-40a1-8c61-4ce60ea41db6"
  Hint: Validate Button
  Value: "{5C9927B1-A837-4C1D-ABF5-5079D816CB26}"
- ID: "337e20e1-999a-4eea-85ad-b58a03ae75cc"
  Hint: Quick Action Bar
  Value: "{5C9927B1-A837-4C1D-ABF5-5079D816CB26}"
- ID: "39847666-389d-409b-95bd-f2016f11eed5"
  Hint: Unversioned
  Value: 1
- ID: "63cb4f24-a2d2-4082-9821-8f350a781e48"
  Hint: Is Required
  Value: 1
- ID: "7ee38888-5f13-4cb1-bad0-09f5b7759856"
  Hint: Specification Searchable
  Value: 0
- ID: "81180d30-1185-426f-ae2d-7da7741399a1"
  Hint: Free Text Searchable
  Value: 0
- ID: "9c903e29-650d-4af2-b9bd-526d5c14a1a5"
  Hint: Validator Bar
  Value: "{5C9927B1-A837-4C1D-ABF5-5079D816CB26}"
- ID: "a0f35a32-14b5-4147-9851-7e0bbdc17efc"
  Hint: Assign To All Product Types
  Value: 0
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Commerce Int64 Control
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 26
- ID: "be351a73-fcb0-4213-93fa-c302d8ab4f51"
  Hint: Shared
  Value: 1
- ID: "d8a78e27-f87f-409b-a4df-d69335dd466f"
  Hint: Base Property
  Value: 0
- ID: "ff45e279-7051-42ad-bf91-117f5ec4bd16"
  Hint: Display On Site
  Value: 0
Languages:
- Language: "de-DE"
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Stockout Threshold
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Stockout Threshold
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: "20140507T120119:635350608791323694"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1bd2b478-a302-49fa-959e-28d6db91788f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        extranet\Anonymous
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170717T130416Z
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Stockout Threshold
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Stockout Threshold
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140507T102935
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8d84e7f1-2516-4432-ab3a-ddc98641e88f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        default\Anonymous
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170717T130455Z
- Language: "fr-FR"
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Seuil de rupture de stock
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Seuil de rupture de stock
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: "20140507T120119:635350608792196856"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e5a9989c-0f79-405f-bc01-c2a9534127b4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20140507T120119:635350608792196856"
- Language: "ja-JP"
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: 在庫切れしきい値
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 在庫切れしきい値
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: "20140507T120119:635350608792816442"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bddae3a0-56d3-44d4-9645-d329aa83f8c2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20140507T120119:635350608792816442"
