#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Rainbow JS CodeGeneration.
//     (https://github.com/asmagin/rainbow-js-codegeneration)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCA.Feature.StoreLocator.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Text;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Configuration;
    using Glass.Mapper.Sc.Fields;
    using Sitecore.Globalization;
    using Sitecore.Data;
    using Sitecore.Data.Items;

    using System.CodeDom.Compiler;
    using HCA.Foundation.GlassMapper.Models;


    /// <summary>
    /// IRadius Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/StoreLocator/Radius</para>
    /// <para>ID: 846425b7-2427-4ba2-ab81-38e895355621</para>
    /// </summary>
    [SitecoreType(TemplateId="846425b7-2427-4ba2-ab81-38e895355621")]
    public partial interface IRadius: IGlassBase
    {

        /// <summary>
        /// The  field.
        /// <para>Field Type: Number</para>
        /// <para>Field ID: 5a040c2d-afc8-41de-aeb9-63a16e889e50</para>
        /// </summary>
        [SitecoreField("Value")]
        float Value {get; set;}

    }


    /// <summary>
    /// Radius Class
    /// <para>Path: /sitecore/templates/HCA/Feature/StoreLocator/Radius</para>
    /// <para>ID: 846425b7-2427-4ba2-ab81-38e895355621</para>
    /// </summary>
    [SitecoreType(TemplateId="846425b7-2427-4ba2-ab81-38e895355621")]
    public partial class Radius: GlassBase, IRadius
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/StoreLocator/Radius
        /// </summary>
        public const string TemplateId = "846425b7-2427-4ba2-ab81-38e895355621";

        /// <summary>
        /// The Value field.
        /// <para>Field Type: Number</para>
        /// <para>Field ID: 5a040c2d-afc8-41de-aeb9-63a16e889e50</para>
        /// </summary>
        [SitecoreField("Value")]
        public virtual float Value {get; set;}
        public const string ValueFieldId = "5a040c2d-afc8-41de-aeb9-63a16e889e50";
        public const string ValueFieldName = "Value";

    }


    /// <summary>
    /// IRadiusesFolder Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/StoreLocator/Radiuses Folder</para>
    /// <para>ID: 7d6a3104-0c1d-42f6-951f-45aa19a8b07b</para>
    /// </summary>
    [SitecoreType(TemplateId="7d6a3104-0c1d-42f6-951f-45aa19a8b07b")]
    public partial interface IRadiusesFolder: IGlassBase
    {

    }


    /// <summary>
    /// RadiusesFolder Class
    /// <para>Path: /sitecore/templates/HCA/Feature/StoreLocator/Radiuses Folder</para>
    /// <para>ID: 7d6a3104-0c1d-42f6-951f-45aa19a8b07b</para>
    /// </summary>
    [SitecoreType(TemplateId="7d6a3104-0c1d-42f6-951f-45aa19a8b07b")]
    public partial class RadiusesFolder: GlassBase, IRadiusesFolder
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/StoreLocator/Radiuses Folder
        /// </summary>
        public const string TemplateId = "7d6a3104-0c1d-42f6-951f-45aa19a8b07b";

    }


    /// <summary>
    /// IStore Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/StoreLocator/Store</para>
    /// <para>ID: 7360d0b3-5400-4dcc-913d-80a4f0d7539e</para>
    /// </summary>
    [SitecoreType(TemplateId="7360d0b3-5400-4dcc-913d-80a4f0d7539e")]
    public partial interface IStore: IGlassBase
    {

    }


    /// <summary>
    /// Store Class
    /// <para>Path: /sitecore/templates/HCA/Feature/StoreLocator/Store</para>
    /// <para>ID: 7360d0b3-5400-4dcc-913d-80a4f0d7539e</para>
    /// </summary>
    [SitecoreType(TemplateId="7360d0b3-5400-4dcc-913d-80a4f0d7539e")]
    public partial class Store: GlassBase, IStore
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/StoreLocator/Store
        /// </summary>
        public const string TemplateId = "7360d0b3-5400-4dcc-913d-80a4f0d7539e";

    }


    /// <summary>
    /// IStoreLocator Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/StoreLocator/Store Locator</para>
    /// <para>ID: dc35377d-4d05-416a-9785-e8e380c75baf</para>
    /// </summary>
    [SitecoreType(TemplateId="dc35377d-4d05-416a-9785-e8e380c75baf")]
    public partial interface IStoreLocator: IGlassBase
    {

        /// <summary>
        /// The  field.
        /// <para>Field Type: Number</para>
        /// <para>Field ID: 42265054-df48-49c4-be6d-4eb68f4f632e</para>
        /// </summary>
        [SitecoreField("Default Latitude")]
        float DefaultLatitude {get; set;}

        /// <summary>
        /// The  field.
        /// <para>Field Type: Number</para>
        /// <para>Field ID: 8c68f0d1-5e42-4e71-a220-2ce4b0cf651c</para>
        /// </summary>
        [SitecoreField("Default Longitude")]
        float DefaultLongitude {get; set;}

        /// <summary>
        /// The  field.
        /// <para>Field Type: Droplink</para>
        /// <para>Field ID: b8df8215-ceb2-4f11-b725-4f5080f4ab18</para>
        /// </summary>
        [SitecoreField("Default Radius")]
        Guid DefaultRadius {get; set;}

        /// <summary>
        /// The  field.
        /// <para>Field Type: Multi-Line Text</para>
        /// <para>Field ID: 50365886-475f-4656-a7d9-bac8bea0c413</para>
        /// </summary>
        [SitecoreField("Description")]
        string Description {get; set;}

        /// <summary>
        /// The  field.
        /// <para>Field Type: Multilist</para>
        /// <para>Field ID: f0d8d855-8257-4096-907f-752b50a62744</para>
        /// </summary>
        [SitecoreField("Radius")]
        IEnumerable<Guid> Radius {get; set;}

        /// <summary>
        /// The  field.
        /// <para>Field Type: Multilist</para>
        /// <para>Field ID: 43aa9312-0033-41de-b127-59379956428f</para>
        /// </summary>
        [SitecoreField("Stores")]
        IEnumerable<Guid> Stores {get; set;}

        /// <summary>
        /// The  field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 0f5d3b8e-badd-4617-9a6d-9102cea617e4</para>
        /// </summary>
        [SitecoreField("Title")]
        string Title {get; set;}

        /// <summary>
        /// The  field.
        /// <para>Field Type: Droplink</para>
        /// <para>Field ID: 506a4f5b-4c6e-466b-8709-b212231977e5</para>
        /// </summary>
        [SitecoreField("Unit Of Length")]
        Guid UnitOfLength {get; set;}

    }


    /// <summary>
    /// StoreLocator Class
    /// <para>Path: /sitecore/templates/HCA/Feature/StoreLocator/Store Locator</para>
    /// <para>ID: dc35377d-4d05-416a-9785-e8e380c75baf</para>
    /// </summary>
    [SitecoreType(TemplateId="dc35377d-4d05-416a-9785-e8e380c75baf")]
    public partial class StoreLocator: GlassBase, IStoreLocator
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/StoreLocator/Store Locator
        /// </summary>
        public const string TemplateId = "dc35377d-4d05-416a-9785-e8e380c75baf";

        /// <summary>
        /// The Default Latitude field.
        /// <para>Field Type: Number</para>
        /// <para>Field ID: 42265054-df48-49c4-be6d-4eb68f4f632e</para>
        /// </summary>
        [SitecoreField("Default Latitude")]
        public virtual float DefaultLatitude {get; set;}
        public const string DefaultLatitudeFieldId = "42265054-df48-49c4-be6d-4eb68f4f632e";
        public const string DefaultLatitudeFieldName = "Default Latitude";

        /// <summary>
        /// The Default Longitude field.
        /// <para>Field Type: Number</para>
        /// <para>Field ID: 8c68f0d1-5e42-4e71-a220-2ce4b0cf651c</para>
        /// </summary>
        [SitecoreField("Default Longitude")]
        public virtual float DefaultLongitude {get; set;}
        public const string DefaultLongitudeFieldId = "8c68f0d1-5e42-4e71-a220-2ce4b0cf651c";
        public const string DefaultLongitudeFieldName = "Default Longitude";

        /// <summary>
        /// The Default Radius field.
        /// <para>Field Type: Droplink</para>
        /// <para>Field ID: b8df8215-ceb2-4f11-b725-4f5080f4ab18</para>
        /// </summary>
        [SitecoreField("Default Radius")]
        public virtual Guid DefaultRadius {get; set;}
        public const string DefaultRadiusFieldId = "b8df8215-ceb2-4f11-b725-4f5080f4ab18";
        public const string DefaultRadiusFieldName = "Default Radius";

        /// <summary>
        /// The Description field.
        /// <para>Field Type: Multi-Line Text</para>
        /// <para>Field ID: 50365886-475f-4656-a7d9-bac8bea0c413</para>
        /// </summary>
        [SitecoreField("Description")]
        public virtual string Description {get; set;}
        public const string DescriptionFieldId = "50365886-475f-4656-a7d9-bac8bea0c413";
        public const string DescriptionFieldName = "Description";

        /// <summary>
        /// The Radius field.
        /// <para>Field Type: Multilist</para>
        /// <para>Field ID: f0d8d855-8257-4096-907f-752b50a62744</para>
        /// </summary>
        [SitecoreField("Radius")]
        public virtual IEnumerable<Guid> Radius {get; set;}
        public const string RadiusFieldId = "f0d8d855-8257-4096-907f-752b50a62744";
        public const string RadiusFieldName = "Radius";

        /// <summary>
        /// The Stores field.
        /// <para>Field Type: Multilist</para>
        /// <para>Field ID: 43aa9312-0033-41de-b127-59379956428f</para>
        /// </summary>
        [SitecoreField("Stores")]
        public virtual IEnumerable<Guid> Stores {get; set;}
        public const string StoresFieldId = "43aa9312-0033-41de-b127-59379956428f";
        public const string StoresFieldName = "Stores";

        /// <summary>
        /// The Title field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 0f5d3b8e-badd-4617-9a6d-9102cea617e4</para>
        /// </summary>
        [SitecoreField("Title")]
        public virtual string Title {get; set;}
        public const string TitleFieldId = "0f5d3b8e-badd-4617-9a6d-9102cea617e4";
        public const string TitleFieldName = "Title";

        /// <summary>
        /// The Unit Of Length field.
        /// <para>Field Type: Droplink</para>
        /// <para>Field ID: 506a4f5b-4c6e-466b-8709-b212231977e5</para>
        /// </summary>
        [SitecoreField("Unit Of Length")]
        public virtual Guid UnitOfLength {get; set;}
        public const string UnitOfLengthFieldId = "506a4f5b-4c6e-466b-8709-b212231977e5";
        public const string UnitOfLengthFieldName = "Unit Of Length";

    }


    /// <summary>
    /// IStoreLocatorFolder Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/StoreLocator/Store Locator Folder</para>
    /// <para>ID: fe957ab9-71b5-4c9f-a34c-1e640acb0abb</para>
    /// </summary>
    [SitecoreType(TemplateId="fe957ab9-71b5-4c9f-a34c-1e640acb0abb")]
    public partial interface IStoreLocatorFolder: IGlassBase
    {

    }


    /// <summary>
    /// StoreLocatorFolder Class
    /// <para>Path: /sitecore/templates/HCA/Feature/StoreLocator/Store Locator Folder</para>
    /// <para>ID: fe957ab9-71b5-4c9f-a34c-1e640acb0abb</para>
    /// </summary>
    [SitecoreType(TemplateId="fe957ab9-71b5-4c9f-a34c-1e640acb0abb")]
    public partial class StoreLocatorFolder: GlassBase, IStoreLocatorFolder
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/StoreLocator/Store Locator Folder
        /// </summary>
        public const string TemplateId = "fe957ab9-71b5-4c9f-a34c-1e640acb0abb";

    }

}