---
ID: "574c656a-bcc1-4520-9eed-acd249e5c47e"
Parent: "4e6f821a-a5cc-4fd5-9ab3-f94a9a785f44"
Template: "4e6f821a-a5cc-4fd5-9ab3-f94a9a785f44"
Path: /sitecore/templates/HCA/Feature/Navigation/Header/Logo Folder/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200528T131529Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
