---
ID: "19806083-db8a-49f2-bf21-f494c65a2976"
Parent: "0d52eb5c-a153-4688-a217-151a17de321e"
Template: "0d52eb5c-a153-4688-a217-151a17de321e"
Path: /sitecore/templates/CommerceConnect/Products/Product Resource/__Standard Values
SharedFields:
- ID: "f7b94d8c-a842-49f8-ab7a-2169d00426b0"
  Hint: __Should Not Organize In Bucket
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20131216T151643
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "aa29ba0c-234a-495e-bfc9-083ff979113e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20150424T145409:635654840493318733Z"
    - ID: "fef7847e-3ac3-4c79-be15-bf407c461de6"
      Hint: Resource
      Value: |
        <image mediaid="{AC9EAEB7-5682-4245-AE38-F4B8393D494B}" />
