//    Copyright 2020 EPAM Systems, Inc.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Rainbow JS CodeGeneration.
//     (https://github.com/asmagin/rainbow-js-codegeneration)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCA.Feature.Account.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Text;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Configuration;
    using Glass.Mapper.Sc.Fields;
    using Sitecore.Globalization;
    using Sitecore.Data;
    using Sitecore.Data.Items;
 
    using System.CodeDom.Compiler;
    using HCA.Foundation.GlassMapper.Models;
    
    
    /// <summary>
    /// IWishlist Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/Account/Wishlist</para>
    /// <para>ID: 689cf1d8-d3d6-4f44-90a6-1525f05d374a</para>
    /// </summary>
    [SitecoreType(TemplateId="689cf1d8-d3d6-4f44-90a6-1525f05d374a")]
    public partial interface IWishlist: IGlassBase
    {
        
        /// <summary>
        /// The Title field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 299aefbb-adfb-425c-9c81-841cc7f7e30f</para>
        /// </summary>
        [SitecoreField("Title")]
        string Title {get; set;}
        
    }
    
    
    /// <summary>
    /// Wishlist Class
    /// <para>Path: /sitecore/templates/HCA/Feature/Account/Wishlist</para>
    /// <para>ID: 689cf1d8-d3d6-4f44-90a6-1525f05d374a</para>
    /// </summary>
    [SitecoreType(TemplateId="689cf1d8-d3d6-4f44-90a6-1525f05d374a")]
    public partial class Wishlist: GlassBase, IWishlist
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/Account/Wishlist
        /// </summary>
        public const string TemplateId = "689cf1d8-d3d6-4f44-90a6-1525f05d374a";

        /// <summary>
        /// The Title field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 299aefbb-adfb-425c-9c81-841cc7f7e30f</para>
        /// </summary>
        [SitecoreField("Title")]
        public virtual string Title {get; set;}
        public const string TitleFieldId = "299aefbb-adfb-425c-9c81-841cc7f7e30f";
        public const string TitleFieldName = "Title";
        
    }
    
    
    /// <summary>
    /// IWishlistFolder Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/Account/Wishlist Folder</para>
    /// <para>ID: 560f6c2d-c8da-4bbb-877d-7fd29f3083b7</para>
    /// </summary>
    [SitecoreType(TemplateId="560f6c2d-c8da-4bbb-877d-7fd29f3083b7")]
    public partial interface IWishlistFolder: IGlassBase
    {
        
    }
    
    
    /// <summary>
    /// WishlistFolder Class
    /// <para>Path: /sitecore/templates/HCA/Feature/Account/Wishlist Folder</para>
    /// <para>ID: 560f6c2d-c8da-4bbb-877d-7fd29f3083b7</para>
    /// </summary>
    [SitecoreType(TemplateId="560f6c2d-c8da-4bbb-877d-7fd29f3083b7")]
    public partial class WishlistFolder: GlassBase, IWishlistFolder
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/Account/Wishlist Folder
        /// </summary>
        public const string TemplateId = "560f6c2d-c8da-4bbb-877d-7fd29f3083b7";

    }
    
}