---
ID: "b8655cbd-077a-4510-a238-f0f0fcc6749a"
Parent: "3fbc5bfa-6e94-493a-9128-f6356f5f3d16"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/HCA/Foundation/Commerce/Configuration/Login/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180528T135953Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0b27766f-cd2a-4666-9e36-c44f0964ce14"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210122T150009Z
