---
ID: "044f856d-261f-4606-9ea4-621e84f10a85"
Parent: "bff2d09d-0b61-4b88-b60b-630d0160b4f4"
Template: "bff2d09d-0b61-4b88-b60b-630d0160b4f4"
Path: /sitecore/templates/CommerceConnect/Sitecore Commerce/Commerce Control Panel/Commerce Engine Settings/Commerce Engine Settings Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{AA15BAD2-8E72-4999-86EF-2B3F0CD1A425}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161127T132336Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7694875e-3925-4dd1-986b-87eda16de06a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20161202T122405Z
