//    Copyright 2020 EPAM Systems, Inc.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Rainbow JS CodeGeneration.
//     (https://github.com/asmagin/rainbow-js-codegeneration)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCA.Feature.PageContent.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Text;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Configuration;
    using Glass.Mapper.Sc.Fields;
    using Sitecore.Globalization;
    using Sitecore.Data;
    using Sitecore.Data.Items;

    using System.CodeDom.Compiler;
    using HCA.Foundation.GlassMapper.Models;


    /// <summary>
    /// IBannerGrid Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Home/Banner Grid</para>
    /// <para>ID: fa4c43ac-9366-44b9-a15c-5ab43c727973</para>
    /// </summary>
    [SitecoreType(TemplateId="fa4c43ac-9366-44b9-a15c-5ab43c727973")]
    public partial interface IBannerGrid: IGlassBase
    {

        /// <summary>
        /// The Main Promo Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: 8e40a2b7-e0dc-43d0-8fcb-91acce9f4480</para>
        /// </summary>
        [SitecoreField("Main Promo Image")]
        Image MainPromoImage {get; set;}

        /// <summary>
        /// The Main Promo Text field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 9e6aa440-a193-4476-b24e-c7e04ac72551</para>
        /// </summary>
        [SitecoreField("Main Promo Text")]
        string MainPromoText {get; set;}

        /// <summary>
        /// The Promo A Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: 91630bb0-eb42-4703-ac9f-0588353f7d73</para>
        /// </summary>
        [SitecoreField("Promo A Image")]
        Image PromoAImage {get; set;}

        /// <summary>
        /// The Promo A Text field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: b432118b-c112-4214-a2ab-64a4776492e0</para>
        /// </summary>
        [SitecoreField("Promo A Text")]
        string PromoAText {get; set;}

        /// <summary>
        /// The Promo B Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: 8280255d-307c-4ae8-8c73-4288a82690a0</para>
        /// </summary>
        [SitecoreField("Promo B Image")]
        Image PromoBImage {get; set;}

        /// <summary>
        /// The Promo C Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: 5b3cc60e-589b-40b7-a54a-4d86bb9853a3</para>
        /// </summary>
        [SitecoreField("Promo C Image")]
        Image PromoCImage {get; set;}

        /// <summary>
        /// The Promo D Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: 56487bee-2b3b-4922-9236-bf351c75ee78</para>
        /// </summary>
        [SitecoreField("Promo D Image")]
        Image PromoDImage {get; set;}

        /// <summary>
        /// The Wide Promo Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: 5e1e9b26-d89e-44e5-a985-168d1c9bda9c</para>
        /// </summary>
        [SitecoreField("Wide Promo Image")]
        Image WidePromoImage {get; set;}

        /// <summary>
        /// The Wide Promo Text field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 4e4e2d3c-032d-47bd-a262-d1262eb71be1</para>
        /// </summary>
        [SitecoreField("Wide Promo Text")]
        string WidePromoText {get; set;}

    }


    /// <summary>
    /// BannerGrid Class
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Home/Banner Grid</para>
    /// <para>ID: fa4c43ac-9366-44b9-a15c-5ab43c727973</para>
    /// </summary>
    [SitecoreType(TemplateId="fa4c43ac-9366-44b9-a15c-5ab43c727973")]
    public partial class BannerGrid: GlassBase, IBannerGrid
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/PageContent/Home/Banner Grid
        /// </summary>
        public const string TemplateId = "fa4c43ac-9366-44b9-a15c-5ab43c727973";

        /// <summary>
        /// The Main Promo Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: 8e40a2b7-e0dc-43d0-8fcb-91acce9f4480</para>
        /// </summary>
        [SitecoreField("Main Promo Image")]
        public virtual Image MainPromoImage {get; set;}
        public const string MainPromoImageFieldId = "8e40a2b7-e0dc-43d0-8fcb-91acce9f4480";
        public const string MainPromoImageFieldName = "Main Promo Image";

        /// <summary>
        /// The Main Promo Text field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 9e6aa440-a193-4476-b24e-c7e04ac72551</para>
        /// </summary>
        [SitecoreField("Main Promo Text")]
        public virtual string MainPromoText {get; set;}
        public const string MainPromoTextFieldId = "9e6aa440-a193-4476-b24e-c7e04ac72551";
        public const string MainPromoTextFieldName = "Main Promo Text";

        /// <summary>
        /// The Promo A Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: 91630bb0-eb42-4703-ac9f-0588353f7d73</para>
        /// </summary>
        [SitecoreField("Promo A Image")]
        public virtual Image PromoAImage {get; set;}
        public const string PromoAImageFieldId = "91630bb0-eb42-4703-ac9f-0588353f7d73";
        public const string PromoAImageFieldName = "Promo A Image";

        /// <summary>
        /// The Promo A Text field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: b432118b-c112-4214-a2ab-64a4776492e0</para>
        /// </summary>
        [SitecoreField("Promo A Text")]
        public virtual string PromoAText {get; set;}
        public const string PromoATextFieldId = "b432118b-c112-4214-a2ab-64a4776492e0";
        public const string PromoATextFieldName = "Promo A Text";

        /// <summary>
        /// The Promo B Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: 8280255d-307c-4ae8-8c73-4288a82690a0</para>
        /// </summary>
        [SitecoreField("Promo B Image")]
        public virtual Image PromoBImage {get; set;}
        public const string PromoBImageFieldId = "8280255d-307c-4ae8-8c73-4288a82690a0";
        public const string PromoBImageFieldName = "Promo B Image";

        /// <summary>
        /// The Promo C Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: 5b3cc60e-589b-40b7-a54a-4d86bb9853a3</para>
        /// </summary>
        [SitecoreField("Promo C Image")]
        public virtual Image PromoCImage {get; set;}
        public const string PromoCImageFieldId = "5b3cc60e-589b-40b7-a54a-4d86bb9853a3";
        public const string PromoCImageFieldName = "Promo C Image";

        /// <summary>
        /// The Promo D Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: 56487bee-2b3b-4922-9236-bf351c75ee78</para>
        /// </summary>
        [SitecoreField("Promo D Image")]
        public virtual Image PromoDImage {get; set;}
        public const string PromoDImageFieldId = "56487bee-2b3b-4922-9236-bf351c75ee78";
        public const string PromoDImageFieldName = "Promo D Image";

        /// <summary>
        /// The Wide Promo Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: 5e1e9b26-d89e-44e5-a985-168d1c9bda9c</para>
        /// </summary>
        [SitecoreField("Wide Promo Image")]
        public virtual Image WidePromoImage {get; set;}
        public const string WidePromoImageFieldId = "5e1e9b26-d89e-44e5-a985-168d1c9bda9c";
        public const string WidePromoImageFieldName = "Wide Promo Image";

        /// <summary>
        /// The Wide Promo Text field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 4e4e2d3c-032d-47bd-a262-d1262eb71be1</para>
        /// </summary>
        [SitecoreField("Wide Promo Text")]
        public virtual string WidePromoText {get; set;}
        public const string WidePromoTextFieldId = "4e4e2d3c-032d-47bd-a262-d1262eb71be1";
        public const string WidePromoTextFieldName = "Wide Promo Text";

    }


    /// <summary>
    /// IGridLayout Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Rendering Parameters/Grid Layout</para>
    /// <para>ID: 61ed6a03-bbdb-4937-87fa-db5c53fc870c</para>
    /// </summary>
    [SitecoreType(TemplateId="61ed6a03-bbdb-4937-87fa-db5c53fc870c")]
    public partial interface IGridLayout: IGlassBase
    {

        /// <summary>
        /// The First Column Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: a10a1cf0-25e7-4b9f-a9ac-6d40de3cbe88</para>
        /// </summary>
        [SitecoreField("First Column Class")]
        string FirstColumnClass {get; set;}

        /// <summary>
        /// The Second Column Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 525bb442-fc9e-49dd-b557-52b833f0855d</para>
        /// </summary>
        [SitecoreField("Second Column Class")]
        string SecondColumnClass {get; set;}

        /// <summary>
        /// The Third Column Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: bfed443f-3ac3-460d-be12-5759b8294233</para>
        /// </summary>
        [SitecoreField("Third Column Class")]
        string ThirdColumnClass {get; set;}

        /// <summary>
        /// The Wrapper Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: b4386ac8-1f1b-49f3-adcb-264f5f595e52</para>
        /// </summary>
        [SitecoreField("Wrapper Class")]
        string WrapperClass {get; set;}

    }


    /// <summary>
    /// GridLayout Class
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Rendering Parameters/Grid Layout</para>
    /// <para>ID: 61ed6a03-bbdb-4937-87fa-db5c53fc870c</para>
    /// </summary>
    [SitecoreType(TemplateId="61ed6a03-bbdb-4937-87fa-db5c53fc870c")]
    public partial class GridLayout: GlassBase, IGridLayout
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/PageContent/Rendering Parameters/Grid Layout
        /// </summary>
        public const string TemplateId = "61ed6a03-bbdb-4937-87fa-db5c53fc870c";

        /// <summary>
        /// The First Column Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: a10a1cf0-25e7-4b9f-a9ac-6d40de3cbe88</para>
        /// </summary>
        [SitecoreField("First Column Class")]
        public virtual string FirstColumnClass {get; set;}
        public const string FirstColumnClassFieldId = "a10a1cf0-25e7-4b9f-a9ac-6d40de3cbe88";
        public const string FirstColumnClassFieldName = "First Column Class";

        /// <summary>
        /// The Second Column Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 525bb442-fc9e-49dd-b557-52b833f0855d</para>
        /// </summary>
        [SitecoreField("Second Column Class")]
        public virtual string SecondColumnClass {get; set;}
        public const string SecondColumnClassFieldId = "525bb442-fc9e-49dd-b557-52b833f0855d";
        public const string SecondColumnClassFieldName = "Second Column Class";

        /// <summary>
        /// The Third Column Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: bfed443f-3ac3-460d-be12-5759b8294233</para>
        /// </summary>
        [SitecoreField("Third Column Class")]
        public virtual string ThirdColumnClass {get; set;}
        public const string ThirdColumnClassFieldId = "bfed443f-3ac3-460d-be12-5759b8294233";
        public const string ThirdColumnClassFieldName = "Third Column Class";

        /// <summary>
        /// The Wrapper Class field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: b4386ac8-1f1b-49f3-adcb-264f5f595e52</para>
        /// </summary>
        [SitecoreField("Wrapper Class")]
        public virtual string WrapperClass {get; set;}
        public const string WrapperClassFieldId = "b4386ac8-1f1b-49f3-adcb-264f5f595e52";
        public const string WrapperClassFieldName = "Wrapper Class";

    }


    /// <summary>
    /// IHomeFolder Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Home/Home Folder</para>
    /// <para>ID: 3c486a78-0beb-48d9-8eb3-9a8f87b5e7e2</para>
    /// </summary>
    [SitecoreType(TemplateId="3c486a78-0beb-48d9-8eb3-9a8f87b5e7e2")]
    public partial interface IHomeFolder: IGlassBase
    {

    }


    /// <summary>
    /// HomeFolder Class
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Home/Home Folder</para>
    /// <para>ID: 3c486a78-0beb-48d9-8eb3-9a8f87b5e7e2</para>
    /// </summary>
    [SitecoreType(TemplateId="3c486a78-0beb-48d9-8eb3-9a8f87b5e7e2")]
    public partial class HomeFolder: GlassBase, IHomeFolder
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/PageContent/Home/Home Folder
        /// </summary>
        public const string TemplateId = "3c486a78-0beb-48d9-8eb3-9a8f87b5e7e2";

    }


    /// <summary>
    /// IRecommendedProducts Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Home/Recommended Products</para>
    /// <para>ID: 02303189-7dc9-41c9-914a-4784878a6a7d</para>
    /// </summary>
    [SitecoreType(TemplateId="02303189-7dc9-41c9-914a-4784878a6a7d")]
    public partial interface IRecommendedProducts: IGlassBase
    {

        /// <summary>
        /// The Header field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: ba9cd774-93ea-490e-b978-38efe2c648ed</para>
        /// </summary>
        [SitecoreField("Header")]
        string Header {get; set;}

    }


    /// <summary>
    /// RecommendedProducts Class
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Home/Recommended Products</para>
    /// <para>ID: 02303189-7dc9-41c9-914a-4784878a6a7d</para>
    /// </summary>
    [SitecoreType(TemplateId="02303189-7dc9-41c9-914a-4784878a6a7d")]
    public partial class RecommendedProducts: GlassBase, IRecommendedProducts
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/PageContent/Home/Recommended Products
        /// </summary>
        public const string TemplateId = "02303189-7dc9-41c9-914a-4784878a6a7d";

        /// <summary>
        /// The Header field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: ba9cd774-93ea-490e-b978-38efe2c648ed</para>
        /// </summary>
        [SitecoreField("Header")]
        public virtual string Header {get; set;}
        public const string HeaderFieldId = "ba9cd774-93ea-490e-b978-38efe2c648ed";
        public const string HeaderFieldName = "Header";

    }

}