---
ID: "242ba0ad-80f4-41c4-a2de-42d7394b0517"
Parent: "1f8158d8-4139-46be-94af-9ff80501f5de"
Template: "1f8158d8-4139-46be-94af-9ff80501f5de"
Path: "/sitecore/templates/CommerceConnect/Sitecore Commerce/Commerce Control Panel/Shared Settings/Countries-Regions/Country-Region/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{CC933745-4840-4BD7-962A-24B27C7ECA6D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161202T072146Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "378a2841-ce42-4127-bbc9-f2352806d514"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20161202T072220Z
