//    Copyright 2020 EPAM Systems, Inc.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Rainbow JS CodeGeneration.
//     (https://github.com/asmagin/rainbow-js-codegeneration)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCA.Foundation.ReactJss.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Text;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Configuration;
    using Glass.Mapper.Sc.Fields;
    using Sitecore.Globalization;
    using Sitecore.Data;
    using Sitecore.Data.Items;

    using System.CodeDom.Compiler;
    using HCA.Foundation.GlassMapper.Models;


    /// <summary>
    /// IImageFallbackSettings Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/ReactJss/Image Fallback Settings</para>
    /// <para>ID: 275950d5-b3a6-476a-8258-bb93a3a96f3c</para>
    /// </summary>
    [SitecoreType(TemplateId="275950d5-b3a6-476a-8258-bb93a3a96f3c")]
    public partial interface IImageFallbackSettings: IGlassBase
    {

        /// <summary>
        /// The Fallback Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: de9c3007-14f7-45bc-b73f-3363f9b4decf</para>
        /// </summary>
        [SitecoreField("Fallback Image")]
        Image FallbackImage {get; set;}

    }


    /// <summary>
    /// ImageFallbackSettings Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/ReactJss/Image Fallback Settings</para>
    /// <para>ID: 275950d5-b3a6-476a-8258-bb93a3a96f3c</para>
    /// </summary>
    [SitecoreType(TemplateId="275950d5-b3a6-476a-8258-bb93a3a96f3c")]
    public partial class ImageFallbackSettings: GlassBase, IImageFallbackSettings
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/ReactJss/Image Fallback Settings
        /// </summary>
        public const string TemplateId = "275950d5-b3a6-476a-8258-bb93a3a96f3c";

        /// <summary>
        /// The Fallback Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: de9c3007-14f7-45bc-b73f-3363f9b4decf</para>
        /// </summary>
        [SitecoreField("Fallback Image")]
        public virtual Image FallbackImage {get; set;}
        public const string FallbackImageFieldId = "de9c3007-14f7-45bc-b73f-3363f9b4decf";
        public const string FallbackImageFieldName = "Fallback Image";

    }

}