---
ID: "763c77c1-09dc-4135-83b3-0470f65105b3"
Parent: "252becf7-cdf0-4cf7-970c-313d1e98c0a1"
Template: "252becf7-cdf0-4cf7-970c-313d1e98c0a1"
Path: /sitecore/templates/HCA/Feature/PageContent/Contact Us/Contact Intro/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210521T142110Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
