---
ID: "d2099843-8f7e-4979-9b35-86827e32417d"
Parent: "e01b4fdd-75cf-4632-84b1-74a75dba4a4f"
Template: "e01b4fdd-75cf-4632-84b1-74a75dba4a4f"
Path: /sitecore/templates/HCA/Feature/PageContent/Advantages/Rendering Parameters/Advantages Rendering Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210723T095421Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a9c7771c-5db4-4b91-abfb-31ed1a9d807a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210811T124442Z
