//    Copyright 2020 EPAM Systems, Inc.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Rainbow JS CodeGeneration.
//     (https://github.com/asmagin/rainbow-js-codegeneration)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCA.Feature.PageContent.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Text;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Configuration;
    using Glass.Mapper.Sc.Fields;
    using Sitecore.Globalization;
    using Sitecore.Data;
    using Sitecore.Data.Items;

    using System.CodeDom.Compiler;
    using HCA.Foundation.GlassMapper.Models;


    /// <summary>
    /// IBanner Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Banner/Banner</para>
    /// <para>ID: aca0aaff-3317-4535-8bc5-504256e08255</para>
    /// </summary>
    [SitecoreType(TemplateId="aca0aaff-3317-4535-8bc5-504256e08255")]
    public partial interface IBanner: IGlassBase
    {

        /// <summary>
        /// The Button Text field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 42ec7cba-9200-49fe-b5f1-03824e1dc337</para>
        /// </summary>
        [SitecoreField("Button Text")]
        string ButtonText {get; set;}

        /// <summary>
        /// The Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: cfb54c8b-6f8e-4bdb-9a07-7df0871196c7</para>
        /// </summary>
        [SitecoreField("Image")]
        Image Image {get; set;}

        /// <summary>
        /// The Link field.
        /// <para>Field Type: General Link</para>
        /// <para>Field ID: ed641b03-6844-4ad0-ae83-ba9d351a2660</para>
        /// </summary>
        [SitecoreField("Link")]
        Link Link {get; set;}

    }


    /// <summary>
    /// Banner Class
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Banner/Banner</para>
    /// <para>ID: aca0aaff-3317-4535-8bc5-504256e08255</para>
    /// </summary>
    [SitecoreType(TemplateId="aca0aaff-3317-4535-8bc5-504256e08255")]
    public partial class Banner: GlassBase, IBanner
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/PageContent/Banner/Banner
        /// </summary>
        public const string TemplateId = "aca0aaff-3317-4535-8bc5-504256e08255";

        /// <summary>
        /// The Button Text field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 42ec7cba-9200-49fe-b5f1-03824e1dc337</para>
        /// </summary>
        [SitecoreField("Button Text")]
        public virtual string ButtonText {get; set;}
        public const string ButtonTextFieldId = "42ec7cba-9200-49fe-b5f1-03824e1dc337";
        public const string ButtonTextFieldName = "Button Text";

        /// <summary>
        /// The Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: cfb54c8b-6f8e-4bdb-9a07-7df0871196c7</para>
        /// </summary>
        [SitecoreField("Image")]
        public virtual Image Image {get; set;}
        public const string ImageFieldId = "cfb54c8b-6f8e-4bdb-9a07-7df0871196c7";
        public const string ImageFieldName = "Image";

        /// <summary>
        /// The Link field.
        /// <para>Field Type: General Link</para>
        /// <para>Field ID: ed641b03-6844-4ad0-ae83-ba9d351a2660</para>
        /// </summary>
        [SitecoreField("Link")]
        public virtual Link Link {get; set;}
        public const string LinkFieldId = "ed641b03-6844-4ad0-ae83-ba9d351a2660";
        public const string LinkFieldName = "Link";

    }


    /// <summary>
    /// IBannerFolder Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Banner/Banner Folder</para>
    /// <para>ID: 60d1329d-bfbf-4c2a-a6be-426f1c700ba9</para>
    /// </summary>
    [SitecoreType(TemplateId="60d1329d-bfbf-4c2a-a6be-426f1c700ba9")]
    public partial interface IBannerFolder: IGlassBase
    {

    }


    /// <summary>
    /// BannerFolder Class
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Banner/Banner Folder</para>
    /// <para>ID: 60d1329d-bfbf-4c2a-a6be-426f1c700ba9</para>
    /// </summary>
    [SitecoreType(TemplateId="60d1329d-bfbf-4c2a-a6be-426f1c700ba9")]
    public partial class BannerFolder: GlassBase, IBannerFolder
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/PageContent/Banner/Banner Folder
        /// </summary>
        public const string TemplateId = "60d1329d-bfbf-4c2a-a6be-426f1c700ba9";

    }


    /// <summary>
    /// ICarouselBanner Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Carousel Banner/Carousel Banner</para>
    /// <para>ID: f3e176b7-c8d9-4c1f-bbe9-e83ce643e0d7</para>
    /// </summary>
    [SitecoreType(TemplateId="f3e176b7-c8d9-4c1f-bbe9-e83ce643e0d7")]
    public partial interface ICarouselBanner: IGlassBase
    {

        /// <summary>
        /// The Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: f335bcc8-a000-4246-b7a5-ebb11e5ffc77</para>
        /// </summary>
        [SitecoreField("Image")]
        Image Image {get; set;}

        /// <summary>
        /// The Link field.
        /// <para>Field Type: General Link</para>
        /// <para>Field ID: 4d22d3fa-f785-4f8c-92eb-b75ab4cf6e4f</para>
        /// </summary>
        [SitecoreField("Link")]
        Link Link {get; set;}

        /// <summary>
        /// The Subtitle field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 1751fa11-d5ca-42c7-b63a-da23a47f37db</para>
        /// </summary>
        [SitecoreField("Subtitle")]
        string Subtitle {get; set;}

        /// <summary>
        /// The Text field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: ab878a5d-cfad-471c-949e-1f590caa233c</para>
        /// </summary>
        [SitecoreField("Text")]
        string Text {get; set;}

        /// <summary>
        /// The Title field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: b2b0d2d9-a822-4647-80c9-0b221b8cb569</para>
        /// </summary>
        [SitecoreField("Title")]
        string Title {get; set;}

    }


    /// <summary>
    /// CarouselBanner Class
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Carousel Banner/Carousel Banner</para>
    /// <para>ID: f3e176b7-c8d9-4c1f-bbe9-e83ce643e0d7</para>
    /// </summary>
    [SitecoreType(TemplateId="f3e176b7-c8d9-4c1f-bbe9-e83ce643e0d7")]
    public partial class CarouselBanner: GlassBase, ICarouselBanner
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/PageContent/Carousel Banner/Carousel Banner
        /// </summary>
        public const string TemplateId = "f3e176b7-c8d9-4c1f-bbe9-e83ce643e0d7";

        /// <summary>
        /// The Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: f335bcc8-a000-4246-b7a5-ebb11e5ffc77</para>
        /// </summary>
        [SitecoreField("Image")]
        public virtual Image Image {get; set;}
        public const string ImageFieldId = "f335bcc8-a000-4246-b7a5-ebb11e5ffc77";
        public const string ImageFieldName = "Image";

        /// <summary>
        /// The Link field.
        /// <para>Field Type: General Link</para>
        /// <para>Field ID: 4d22d3fa-f785-4f8c-92eb-b75ab4cf6e4f</para>
        /// </summary>
        [SitecoreField("Link")]
        public virtual Link Link {get; set;}
        public const string LinkFieldId = "4d22d3fa-f785-4f8c-92eb-b75ab4cf6e4f";
        public const string LinkFieldName = "Link";

        /// <summary>
        /// The Subtitle field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 1751fa11-d5ca-42c7-b63a-da23a47f37db</para>
        /// </summary>
        [SitecoreField("Subtitle")]
        public virtual string Subtitle {get; set;}
        public const string SubtitleFieldId = "1751fa11-d5ca-42c7-b63a-da23a47f37db";
        public const string SubtitleFieldName = "Subtitle";

        /// <summary>
        /// The Text field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: ab878a5d-cfad-471c-949e-1f590caa233c</para>
        /// </summary>
        [SitecoreField("Text")]
        public virtual string Text {get; set;}
        public const string TextFieldId = "ab878a5d-cfad-471c-949e-1f590caa233c";
        public const string TextFieldName = "Text";

        /// <summary>
        /// The Title field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: b2b0d2d9-a822-4647-80c9-0b221b8cb569</para>
        /// </summary>
        [SitecoreField("Title")]
        public virtual string Title {get; set;}
        public const string TitleFieldId = "b2b0d2d9-a822-4647-80c9-0b221b8cb569";
        public const string TitleFieldName = "Title";

    }


    /// <summary>
    /// ICarouselBannerFolder Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Carousel Banner/Carousel Banner Folder</para>
    /// <para>ID: 764f7c1b-1d67-43fb-9074-df87a0deb60e</para>
    /// </summary>
    [SitecoreType(TemplateId="764f7c1b-1d67-43fb-9074-df87a0deb60e")]
    public partial interface ICarouselBannerFolder: IGlassBase
    {

        /// <summary>
        /// The Banners field.
        /// <para>Field Type: Multilist</para>
        /// <para>Field ID: e7bbd25a-3f42-4199-9e19-19a87b7020e7</para>
        /// </summary>
        [SitecoreField("Banners")]
        IEnumerable<Guid> Banners {get; set;}

    }


    /// <summary>
    /// CarouselBannerFolder Class
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Carousel Banner/Carousel Banner Folder</para>
    /// <para>ID: 764f7c1b-1d67-43fb-9074-df87a0deb60e</para>
    /// </summary>
    [SitecoreType(TemplateId="764f7c1b-1d67-43fb-9074-df87a0deb60e")]
    public partial class CarouselBannerFolder: GlassBase, ICarouselBannerFolder
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/PageContent/Carousel Banner/Carousel Banner Folder
        /// </summary>
        public const string TemplateId = "764f7c1b-1d67-43fb-9074-df87a0deb60e";

        /// <summary>
        /// The Banners field.
        /// <para>Field Type: Multilist</para>
        /// <para>Field ID: e7bbd25a-3f42-4199-9e19-19a87b7020e7</para>
        /// </summary>
        [SitecoreField("Banners")]
        public virtual IEnumerable<Guid> Banners {get; set;}
        public const string BannersFieldId = "e7bbd25a-3f42-4199-9e19-19a87b7020e7";
        public const string BannersFieldName = "Banners";

    }


    /// <summary>
    /// IRecommendedProducts Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Recommended Products/Recommended Products</para>
    /// <para>ID: 02303189-7dc9-41c9-914a-4784878a6a7d</para>
    /// </summary>
    [SitecoreType(TemplateId="02303189-7dc9-41c9-914a-4784878a6a7d")]
    public partial interface IRecommendedProducts: IGlassBase
    {

        /// <summary>
        /// The Header field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: ba9cd774-93ea-490e-b978-38efe2c648ed</para>
        /// </summary>
        [SitecoreField("Header")]
        string Header {get; set;}

    }


    /// <summary>
    /// RecommendedProducts Class
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Recommended Products/Recommended Products</para>
    /// <para>ID: 02303189-7dc9-41c9-914a-4784878a6a7d</para>
    /// </summary>
    [SitecoreType(TemplateId="02303189-7dc9-41c9-914a-4784878a6a7d")]
    public partial class RecommendedProducts: GlassBase, IRecommendedProducts
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/PageContent/Recommended Products/Recommended Products
        /// </summary>
        public const string TemplateId = "02303189-7dc9-41c9-914a-4784878a6a7d";

        /// <summary>
        /// The Header field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: ba9cd774-93ea-490e-b978-38efe2c648ed</para>
        /// </summary>
        [SitecoreField("Header")]
        public virtual string Header {get; set;}
        public const string HeaderFieldId = "ba9cd774-93ea-490e-b978-38efe2c648ed";
        public const string HeaderFieldName = "Header";

    }


    /// <summary>
    /// IRecommendedProductsFolder Interface
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Recommended Products/Recommended Products Folder</para>
    /// <para>ID: 2ef7b0f6-a5e5-43e6-acec-0f1c2eed1731</para>
    /// </summary>
    [SitecoreType(TemplateId="2ef7b0f6-a5e5-43e6-acec-0f1c2eed1731")]
    public partial interface IRecommendedProductsFolder: IGlassBase
    {

    }


    /// <summary>
    /// RecommendedProductsFolder Class
    /// <para>Path: /sitecore/templates/HCA/Feature/PageContent/Recommended Products/Recommended Products Folder</para>
    /// <para>ID: 2ef7b0f6-a5e5-43e6-acec-0f1c2eed1731</para>
    /// </summary>
    [SitecoreType(TemplateId="2ef7b0f6-a5e5-43e6-acec-0f1c2eed1731")]
    public partial class RecommendedProductsFolder: GlassBase, IRecommendedProductsFolder
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Feature/PageContent/Recommended Products/Recommended Products Folder
        /// </summary>
        public const string TemplateId = "2ef7b0f6-a5e5-43e6-acec-0f1c2eed1731";

    }

}