//    Copyright 2020 EPAM Systems, Inc.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Rainbow JS CodeGeneration.
//     (https://github.com/asmagin/rainbow-js-codegeneration)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCA.Foundation.Commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Text;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Configuration;
    using Glass.Mapper.Sc.Fields;
    using Sitecore.Globalization;
    using Sitecore.Data;
    using Sitecore.Data.Items;

    using System.CodeDom.Compiler;
    using HCA.Foundation.GlassMapper.Models;


    /// <summary>
    /// IHomePageConfiguration Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/Commerce/Configuration/Home Page Configuration</para>
    /// <para>ID: c188ca00-aaa5-4385-bb4e-60d7e0244e4c</para>
    /// </summary>
    [SitecoreType(TemplateId="c188ca00-aaa5-4385-bb4e-60d7e0244e4c")]
    public partial interface IHomePageConfiguration: IGlassBase
    {

        /// <summary>
        /// The Control Panel Configuration field.
        /// <para>Field Type: Droptree</para>
        /// <para>Field ID: cf39528f-dcd5-489c-8188-6d8980d903e3</para>
        /// </summary>
        [SitecoreField("Control Panel Configuration")]
        Guid ControlPanelConfiguration {get; set;}

    }


    /// <summary>
    /// HomePageConfiguration Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/Commerce/Configuration/Home Page Configuration</para>
    /// <para>ID: c188ca00-aaa5-4385-bb4e-60d7e0244e4c</para>
    /// </summary>
    [SitecoreType(TemplateId="c188ca00-aaa5-4385-bb4e-60d7e0244e4c")]
    public partial class HomePageConfiguration: GlassBase, IHomePageConfiguration
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/Commerce/Configuration/Home Page Configuration
        /// </summary>
        public const string TemplateId = "c188ca00-aaa5-4385-bb4e-60d7e0244e4c";

        /// <summary>
        /// The Control Panel Configuration field.
        /// <para>Field Type: Droptree</para>
        /// <para>Field ID: cf39528f-dcd5-489c-8188-6d8980d903e3</para>
        /// </summary>
        [SitecoreField("Control Panel Configuration")]
        public virtual Guid ControlPanelConfiguration {get; set;}
        public const string ControlPanelConfigurationFieldId = "cf39528f-dcd5-489c-8188-6d8980d903e3";
        public const string ControlPanelConfigurationFieldName = "Control Panel Configuration";

    }


    /// <summary>
    /// ILogin Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/Commerce/Configuration/Login</para>
    /// <para>ID: 3fbc5bfa-6e94-493a-9128-f6356f5f3d16</para>
    /// </summary>
    [SitecoreType(TemplateId="3fbc5bfa-6e94-493a-9128-f6356f5f3d16")]
    public partial interface ILogin: IGlassBase
    {

        /// <summary>
        /// The DefaultUser field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: b99ca0c7-ee56-466b-99e5-d30dfddb75ae</para>
        /// </summary>
        [SitecoreField("DefaultUser")]
        string DefaultUser {get; set;}

    }


    /// <summary>
    /// Login Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/Commerce/Configuration/Login</para>
    /// <para>ID: 3fbc5bfa-6e94-493a-9128-f6356f5f3d16</para>
    /// </summary>
    [SitecoreType(TemplateId="3fbc5bfa-6e94-493a-9128-f6356f5f3d16")]
    public partial class Login: GlassBase, ILogin
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/Commerce/Configuration/Login
        /// </summary>
        public const string TemplateId = "3fbc5bfa-6e94-493a-9128-f6356f5f3d16";

        /// <summary>
        /// The DefaultUser field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: b99ca0c7-ee56-466b-99e5-d30dfddb75ae</para>
        /// </summary>
        [SitecoreField("DefaultUser")]
        public virtual string DefaultUser {get; set;}
        public const string DefaultUserFieldId = "b99ca0c7-ee56-466b-99e5-d30dfddb75ae";
        public const string DefaultUserFieldName = "DefaultUser";

    }


    /// <summary>
    /// ICategoryItem Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/Commerce/Context Resolving/_Category Item</para>
    /// <para>ID: f5ea378c-547f-4482-9de6-14eb416a9b30</para>
    /// </summary>
    [SitecoreType(TemplateId="f5ea378c-547f-4482-9de6-14eb416a9b30")]
    public partial interface ICategoryItem: IGlassBase
    {

    }


    /// <summary>
    /// CategoryItem Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/Commerce/Context Resolving/_Category Item</para>
    /// <para>ID: f5ea378c-547f-4482-9de6-14eb416a9b30</para>
    /// </summary>
    [SitecoreType(TemplateId="f5ea378c-547f-4482-9de6-14eb416a9b30")]
    public partial class CategoryItem: GlassBase, ICategoryItem
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/Commerce/Context Resolving/_Category Item
        /// </summary>
        public const string TemplateId = "f5ea378c-547f-4482-9de6-14eb416a9b30";

    }


    /// <summary>
    /// IProductItem Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/Commerce/Context Resolving/_Product Item</para>
    /// <para>ID: 97fb3bfc-0774-495c-99f6-c63739985173</para>
    /// </summary>
    [SitecoreType(TemplateId="97fb3bfc-0774-495c-99f6-c63739985173")]
    public partial interface IProductItem: IGlassBase
    {

    }


    /// <summary>
    /// ProductItem Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/Commerce/Context Resolving/_Product Item</para>
    /// <para>ID: 97fb3bfc-0774-495c-99f6-c63739985173</para>
    /// </summary>
    [SitecoreType(TemplateId="97fb3bfc-0774-495c-99f6-c63739985173")]
    public partial class ProductItem: GlassBase, IProductItem
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/Commerce/Context Resolving/_Product Item
        /// </summary>
        public const string TemplateId = "97fb3bfc-0774-495c-99f6-c63739985173";

    }

}