---
ID: "b498bd53-c210-4844-a523-56ad9ec4ae5d"
Parent: "93703013-77b6-48b5-8338-c29a5d15a1a6"
Template: "93703013-77b6-48b5-8338-c29a5d15a1a6"
Path: /sitecore/templates/CommerceConnect/Products/Product Relation/__Standard Values
SharedFields:
- ID: "f7b94d8c-a842-49f8-ab7a-2169d00426b0"
  Hint: __Should Not Organize In Bucket
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1ac1bfa4-4113-4c66-afe2-f3f3c0266c73"
      Hint: Name
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130508T145800
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9c275337-e38b-4186-b15c-23f7c0e04caf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20131216T151624:635228037845899827"
