---
ID: "8dfc2e1f-425a-48fe-838f-e72a98d000b0"
Parent: "284f5f48-7d2e-48d3-b3f5-c8f45549a2a0"
Template: "284f5f48-7d2e-48d3-b3f5-c8f45549a2a0"
Path: /sitecore/templates/CommerceConnect/Products/Specification/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "02eaa1d4-a90a-4124-b2ba-3453794daf10"
      Hint: Name
      Value: $Name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130514T115237
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1d952bfc-887b-42f1-af13-06f6d6837042"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20130722T142547:635100999477655613"
