---
ID: "26fede9c-43f0-4246-a5ab-39c7acb45c49"
Parent: "49f79318-adc9-492b-82f2-e29fa8f5dfb1"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/HCA/Feature/Navigation/Social Network Links/Social Networks Links Params/Params
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201224T075358Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1e0c09b0-e693-4e9c-bf27-297057dc166b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210122T150022Z
