---
ID: "805ac07b-53aa-4e03-978d-b114b069e98e"
Parent: "5d7682df-27d9-4fc9-bb4e-7ac06d7bbd7c"
Template: "81afaa32-f1b0-47de-a8e6-3e443a06510e"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/HCA/Currency Configuration
SharedFields:
- ID: "f8abfa72-0fba-44a5-9122-cf11acb0ea61"
  Hint: Currency Set
  Value: "{0F65742E-317F-44B0-A4DE-EBF06209E8EE}"
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Currency Configuration
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171123T163820Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "952884be-422e-46e5-9bf2-807cae484c9a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200420T093523Z
