//    Copyright 2020 EPAM Systems, Inc.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Rainbow JS CodeGeneration.
//     (https://github.com/asmagin/rainbow-js-codegeneration)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCA.Foundation.UI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Text;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Configuration;
    using Glass.Mapper.Sc.Fields;
    using Sitecore.Globalization;
    using Sitecore.Data;
    using Sitecore.Data.Items;

    using System.CodeDom.Compiler;
    using HCA.Foundation.GlassMapper.Models;


    /// <summary>
    /// IFilterType Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/Filter/Filter Type</para>
    /// <para>ID: f9a592be-29fc-4e37-b5e4-8c4df04b3d61</para>
    /// </summary>
    [SitecoreType(TemplateId="f9a592be-29fc-4e37-b5e4-8c4df04b3d61")]
    public partial interface IFilterType: IGlassBase
    {

    }


    /// <summary>
    /// FilterType Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/Filter/Filter Type</para>
    /// <para>ID: f9a592be-29fc-4e37-b5e4-8c4df04b3d61</para>
    /// </summary>
    [SitecoreType(TemplateId="f9a592be-29fc-4e37-b5e4-8c4df04b3d61")]
    public partial class FilterType: GlassBase, IFilterType
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/UI/Filter/Filter Type
        /// </summary>
        public const string TemplateId = "f9a592be-29fc-4e37-b5e4-8c4df04b3d61";

    }


    /// <summary>
    /// IFilterTypes Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/Filter/Filter Types</para>
    /// <para>ID: 844a2cf8-2dd3-468f-820a-f79dec4481d4</para>
    /// </summary>
    [SitecoreType(TemplateId="844a2cf8-2dd3-468f-820a-f79dec4481d4")]
    public partial interface IFilterTypes: IGlassBase
    {

    }


    /// <summary>
    /// FilterTypes Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/Filter/Filter Types</para>
    /// <para>ID: 844a2cf8-2dd3-468f-820a-f79dec4481d4</para>
    /// </summary>
    [SitecoreType(TemplateId="844a2cf8-2dd3-468f-820a-f79dec4481d4")]
    public partial class FilterTypes: GlassBase, IFilterTypes
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/UI/Filter/Filter Types
        /// </summary>
        public const string TemplateId = "844a2cf8-2dd3-468f-820a-f79dec4481d4";

    }


    /// <summary>
    /// IFilter Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/Filter/_Filter</para>
    /// <para>ID: 038e0285-d2e8-4439-892e-00cb667441e9</para>
    /// </summary>
    [SitecoreType(TemplateId="038e0285-d2e8-4439-892e-00cb667441e9")]
    public partial interface IFilter: IGlassBase
    {

        /// <summary>
        /// The Filter Type field.
        /// <para>Field Type: Droplist</para>
        /// <para>Field ID: c7ff496e-141b-4b03-80e4-e1eedae5470d</para>
        /// </summary>
        [SitecoreField("Filter Type")]
        string FilterType {get; set;}

    }


    /// <summary>
    /// Filter Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/Filter/_Filter</para>
    /// <para>ID: 038e0285-d2e8-4439-892e-00cb667441e9</para>
    /// </summary>
    [SitecoreType(TemplateId="038e0285-d2e8-4439-892e-00cb667441e9")]
    public partial class Filter: GlassBase, IFilter
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/UI/Filter/_Filter
        /// </summary>
        public const string TemplateId = "038e0285-d2e8-4439-892e-00cb667441e9";

        /// <summary>
        /// The Filter Type field.
        /// <para>Field Type: Droplist</para>
        /// <para>Field ID: c7ff496e-141b-4b03-80e4-e1eedae5470d</para>
        /// </summary>
        [SitecoreField("Filter Type")]
        public virtual string FilterType {get; set;}
        public const string FilterTypeFieldId = "c7ff496e-141b-4b03-80e4-e1eedae5470d";
        public const string FilterTypeFieldName = "Filter Type";

    }

}