//    Copyright 2020 EPAM Systems, Inc.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Rainbow JS CodeGeneration.
//     (https://github.com/asmagin/rainbow-js-codegeneration)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCA.Foundation.UI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Text;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Configuration;
    using Glass.Mapper.Sc.Fields;
    using Sitecore.Globalization;
    using Sitecore.Data;
    using Sitecore.Data.Items;

    using System.CodeDom.Compiler;
    using HCA.Foundation.GlassMapper.Models;


    /// <summary>
    /// IFilterType Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/Filter/Filter Type</para>
    /// <para>ID: f9a592be-29fc-4e37-b5e4-8c4df04b3d61</para>
    /// </summary>
    [SitecoreType(TemplateId="f9a592be-29fc-4e37-b5e4-8c4df04b3d61")]
    public partial interface IFilterType: IGlassBase
    {

    }


    /// <summary>
    /// FilterType Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/Filter/Filter Type</para>
    /// <para>ID: f9a592be-29fc-4e37-b5e4-8c4df04b3d61</para>
    /// </summary>
    [SitecoreType(TemplateId="f9a592be-29fc-4e37-b5e4-8c4df04b3d61")]
    public partial class FilterType: GlassBase, IFilterType
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/UI/Filter/Filter Type
        /// </summary>
        public const string TemplateId = "f9a592be-29fc-4e37-b5e4-8c4df04b3d61";

    }


    /// <summary>
    /// IFilterTypes Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/Filter/Filter Types</para>
    /// <para>ID: 844a2cf8-2dd3-468f-820a-f79dec4481d4</para>
    /// </summary>
    [SitecoreType(TemplateId="844a2cf8-2dd3-468f-820a-f79dec4481d4")]
    public partial interface IFilterTypes: IGlassBase
    {

    }


    /// <summary>
    /// FilterTypes Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/Filter/Filter Types</para>
    /// <para>ID: 844a2cf8-2dd3-468f-820a-f79dec4481d4</para>
    /// </summary>
    [SitecoreType(TemplateId="844a2cf8-2dd3-468f-820a-f79dec4481d4")]
    public partial class FilterTypes: GlassBase, IFilterTypes
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/UI/Filter/Filter Types
        /// </summary>
        public const string TemplateId = "844a2cf8-2dd3-468f-820a-f79dec4481d4";

    }


    /// <summary>
    /// INoResultsFound Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/No Results Found/No Results Found</para>
    /// <para>ID: 1973dfe5-c0a3-471a-9a4e-5a3922a38c49</para>
    /// </summary>
    [SitecoreType(TemplateId="1973dfe5-c0a3-471a-9a4e-5a3922a38c49")]
    public partial interface INoResultsFound: IGlassBase
    {

        /// <summary>
        /// The Header Line field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: f1de21b2-57b8-4286-ad5f-01d5001614c7</para>
        /// </summary>
        [SitecoreField("Header Line")]
        string HeaderLine {get; set;}

        /// <summary>
        /// The Tips field.
        /// <para>Field Type: Multilist</para>
        /// <para>Field ID: cc774dab-368c-4aac-a344-75cf54d14760</para>
        /// </summary>
        [SitecoreField("Tips")]
        IEnumerable<Guid> Tips {get; set;}

        /// <summary>
        /// The Tips Header field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 32ec9797-99f5-40d5-8aaa-71506aeb3dbc</para>
        /// </summary>
        [SitecoreField("Tips Header")]
        string TipsHeader {get; set;}

    }


    /// <summary>
    /// NoResultsFound Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/No Results Found/No Results Found</para>
    /// <para>ID: 1973dfe5-c0a3-471a-9a4e-5a3922a38c49</para>
    /// </summary>
    [SitecoreType(TemplateId="1973dfe5-c0a3-471a-9a4e-5a3922a38c49")]
    public partial class NoResultsFound: GlassBase, INoResultsFound
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/UI/No Results Found/No Results Found
        /// </summary>
        public const string TemplateId = "1973dfe5-c0a3-471a-9a4e-5a3922a38c49";

        /// <summary>
        /// The Header Line field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: f1de21b2-57b8-4286-ad5f-01d5001614c7</para>
        /// </summary>
        [SitecoreField("Header Line")]
        public virtual string HeaderLine {get; set;}
        public const string HeaderLineFieldId = "f1de21b2-57b8-4286-ad5f-01d5001614c7";
        public const string HeaderLineFieldName = "Header Line";

        /// <summary>
        /// The Tips field.
        /// <para>Field Type: Multilist</para>
        /// <para>Field ID: cc774dab-368c-4aac-a344-75cf54d14760</para>
        /// </summary>
        [SitecoreField("Tips")]
        public virtual IEnumerable<Guid> Tips {get; set;}
        public const string TipsFieldId = "cc774dab-368c-4aac-a344-75cf54d14760";
        public const string TipsFieldName = "Tips";

        /// <summary>
        /// The Tips Header field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 32ec9797-99f5-40d5-8aaa-71506aeb3dbc</para>
        /// </summary>
        [SitecoreField("Tips Header")]
        public virtual string TipsHeader {get; set;}
        public const string TipsHeaderFieldId = "32ec9797-99f5-40d5-8aaa-71506aeb3dbc";
        public const string TipsHeaderFieldName = "Tips Header";

    }


    /// <summary>
    /// INoResultsFoundFolder Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/No Results Found/No Results Found Folder</para>
    /// <para>ID: 22ada616-bdfa-4d4c-bdfb-8e33616bc3c0</para>
    /// </summary>
    [SitecoreType(TemplateId="22ada616-bdfa-4d4c-bdfb-8e33616bc3c0")]
    public partial interface INoResultsFoundFolder: IGlassBase
    {

    }


    /// <summary>
    /// NoResultsFoundFolder Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/No Results Found/No Results Found Folder</para>
    /// <para>ID: 22ada616-bdfa-4d4c-bdfb-8e33616bc3c0</para>
    /// </summary>
    [SitecoreType(TemplateId="22ada616-bdfa-4d4c-bdfb-8e33616bc3c0")]
    public partial class NoResultsFoundFolder: GlassBase, INoResultsFoundFolder
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/UI/No Results Found/No Results Found Folder
        /// </summary>
        public const string TemplateId = "22ada616-bdfa-4d4c-bdfb-8e33616bc3c0";

    }


    /// <summary>
    /// ISearchTip Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/No Results Found/Search Tip</para>
    /// <para>ID: 826a09fd-613e-4280-86df-36a1548baeb0</para>
    /// </summary>
    [SitecoreType(TemplateId="826a09fd-613e-4280-86df-36a1548baeb0")]
    public partial interface ISearchTip: IGlassBase
    {

        /// <summary>
        /// The Tip field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 6f4cf02f-963d-45be-afec-7903db6e2248</para>
        /// </summary>
        [SitecoreField("Tip")]
        string Tip {get; set;}

    }


    /// <summary>
    /// SearchTip Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/No Results Found/Search Tip</para>
    /// <para>ID: 826a09fd-613e-4280-86df-36a1548baeb0</para>
    /// </summary>
    [SitecoreType(TemplateId="826a09fd-613e-4280-86df-36a1548baeb0")]
    public partial class SearchTip: GlassBase, ISearchTip
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/UI/No Results Found/Search Tip
        /// </summary>
        public const string TemplateId = "826a09fd-613e-4280-86df-36a1548baeb0";

        /// <summary>
        /// The Tip field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 6f4cf02f-963d-45be-afec-7903db6e2248</para>
        /// </summary>
        [SitecoreField("Tip")]
        public virtual string Tip {get; set;}
        public const string TipFieldId = "6f4cf02f-963d-45be-afec-7903db6e2248";
        public const string TipFieldName = "Tip";

    }


    /// <summary>
    /// ISearchTips Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/No Results Found/Search Tips</para>
    /// <para>ID: 2508d62c-70e1-4962-b606-27a5ee4ac020</para>
    /// </summary>
    [SitecoreType(TemplateId="2508d62c-70e1-4962-b606-27a5ee4ac020")]
    public partial interface ISearchTips: IGlassBase
    {

    }


    /// <summary>
    /// SearchTips Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/No Results Found/Search Tips</para>
    /// <para>ID: 2508d62c-70e1-4962-b606-27a5ee4ac020</para>
    /// </summary>
    [SitecoreType(TemplateId="2508d62c-70e1-4962-b606-27a5ee4ac020")]
    public partial class SearchTips: GlassBase, ISearchTips
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/UI/No Results Found/Search Tips
        /// </summary>
        public const string TemplateId = "2508d62c-70e1-4962-b606-27a5ee4ac020";

    }


    /// <summary>
    /// IFilter Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/Filter/_Filter</para>
    /// <para>ID: 038e0285-d2e8-4439-892e-00cb667441e9</para>
    /// </summary>
    [SitecoreType(TemplateId="038e0285-d2e8-4439-892e-00cb667441e9")]
    public partial interface IFilter: IGlassBase
    {

        /// <summary>
        /// The Filter Type field.
        /// <para>Field Type: Droplist</para>
        /// <para>Field ID: c7ff496e-141b-4b03-80e4-e1eedae5470d</para>
        /// </summary>
        [SitecoreField("Filter Type")]
        string FilterType {get; set;}

    }


    /// <summary>
    /// Filter Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/UI/Filter/_Filter</para>
    /// <para>ID: 038e0285-d2e8-4439-892e-00cb667441e9</para>
    /// </summary>
    [SitecoreType(TemplateId="038e0285-d2e8-4439-892e-00cb667441e9")]
    public partial class Filter: GlassBase, IFilter
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/UI/Filter/_Filter
        /// </summary>
        public const string TemplateId = "038e0285-d2e8-4439-892e-00cb667441e9";

        /// <summary>
        /// The Filter Type field.
        /// <para>Field Type: Droplist</para>
        /// <para>Field ID: c7ff496e-141b-4b03-80e4-e1eedae5470d</para>
        /// </summary>
        [SitecoreField("Filter Type")]
        public virtual string FilterType {get; set;}
        public const string FilterTypeFieldId = "c7ff496e-141b-4b03-80e4-e1eedae5470d";
        public const string FilterTypeFieldName = "Filter Type";

    }

}