---
ID: "15d4267c-b68d-45de-9bd8-c28ef59c4de4"
Parent: "fa4c43ac-9366-44b9-a15c-5ab43c727973"
Template: "fa4c43ac-9366-44b9-a15c-5ab43c727973"
Path: /sitecore/templates/HCA/Feature/PageContent/Home/Banner Grid/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200519T114908Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
