//    Copyright 2020 EPAM Systems, Inc.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Rainbow JS CodeGeneration.
//     (https://github.com/asmagin/rainbow-js-codegeneration)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCA.Foundation.Base.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Text;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Configuration;
    using Glass.Mapper.Sc.Fields;
    using Sitecore.Globalization;
    using Sitecore.Data;
    using Sitecore.Data.Items;

    using System.CodeDom.Compiler;
    using HCA.Foundation.GlassMapper.Models;


    /// <summary>
    /// ISiteSettings Interface
    /// <para>Path: /sitecore/templates/HCA/Foundation/Base/_SiteSettings</para>
    /// <para>ID: 7724bf37-c8c6-4189-b7c9-7ed566ac76d8</para>
    /// </summary>
    [SitecoreType(TemplateId="7724bf37-c8c6-4189-b7c9-7ed566ac76d8")]
    public partial interface ISiteSettings: IGlassBase
    {

    }


    /// <summary>
    /// SiteSettings Class
    /// <para>Path: /sitecore/templates/HCA/Foundation/Base/_SiteSettings</para>
    /// <para>ID: 7724bf37-c8c6-4189-b7c9-7ed566ac76d8</para>
    /// </summary>
    [SitecoreType(TemplateId="7724bf37-c8c6-4189-b7c9-7ed566ac76d8")]
    public partial class SiteSettings: GlassBase, ISiteSettings
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/HCA/Foundation/Base/_SiteSettings
        /// </summary>
        public const string TemplateId = "7724bf37-c8c6-4189-b7c9-7ed566ac76d8";

    }

}