---
ID: "0c521339-a7b6-4966-a0ed-e2b4d2701b0f"
Parent: "7724bf37-c8c6-4189-b7c9-7ed566ac76d8"
Template: "7724bf37-c8c6-4189-b7c9-7ed566ac76d8"
Path: /sitecore/templates/HCA/Foundation/Base/_SiteSettings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200529T082653Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
