---
ID: "028237bc-c9f0-4c68-b130-49dd02c44f16"
Parent: "bec7a22d-95bd-49d9-9715-5a2307110139"
Template: "c8206dfc-92cd-4bee-afa3-3c86f340665a"
Path: /sitecore/Commerce/Commerce Control Panel/Shared Settings/Indexing Settings
SharedFields:
- ID: "caffd21c-01dc-4d67-9426-752f5cca21c4"
  Hint: ExcludeDuplicateSearchResults
  Value: 1
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Indexing Settings
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190308T174004Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8ab1b1d2-53b9-415a-9923-cb2c1d190f57"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210122T150100Z
