---
ID: "f0620f1e-53a9-4904-8da5-a4747ec5b509"
Parent: "1e890498-c6cc-440a-9fbc-397d0e998b59"
Template: "1e890498-c6cc-440a-9fbc-397d0e998b59"
Path: /sitecore/templates/HCA/Feature/PageContent/Contact Us/Contact Links/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{C140817D-2718-4C74-8F0F-46D220B0FA91}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201216T205845Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
