//    Copyright 2019 EPAM Systems, Inc.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Rainbow JS CodeGeneration.
//     (https://github.com/asmagin/rainbow-js-codegeneration)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wooli.Feature.Navigation.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Text;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Configuration;
    using Glass.Mapper.Sc.Fields;
    using Sitecore.Globalization;
    using Sitecore.Data;
    using Sitecore.Data.Items;

    using System.CodeDom.Compiler;
    using Wooli.Foundation.GlassMapper.Models;


    /// <summary>
    /// IGlobalHeader Interface
    /// <para>Path: /sitecore/templates/Wooli/Feature/Navigation/Global Header</para>
    /// <para>ID: 77eee1b3-ede2-41fc-b2fe-1f77832e09e5</para>
    /// </summary>
    [SitecoreType(TemplateId="77eee1b3-ede2-41fc-b2fe-1f77832e09e5")]
    public partial interface IGlobalHeader: IGlassBase
    {

        /// <summary>
        /// The Menu Items field.
        /// <para>Field Type: Multilist</para>
        /// <para>Field ID: 35033e47-38f6-4912-b14d-e23b5c7390d7</para>
        /// </summary>
        [SitecoreField("Menu Items")]
        IEnumerable<Guid> MenuItems {get; set;}

    }


    /// <summary>
    /// GlobalHeader Class
    /// <para>Path: /sitecore/templates/Wooli/Feature/Navigation/Global Header</para>
    /// <para>ID: 77eee1b3-ede2-41fc-b2fe-1f77832e09e5</para>
    /// </summary>
    [SitecoreType(TemplateId="77eee1b3-ede2-41fc-b2fe-1f77832e09e5")]
    public partial class GlobalHeader: GlassBase, IGlobalHeader
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/Wooli/Feature/Navigation/Global Header
        /// </summary>
        public const string TemplateId = "77eee1b3-ede2-41fc-b2fe-1f77832e09e5";

        /// <summary>
        /// The Menu Items field.
        /// <para>Field Type: Multilist</para>
        /// <para>Field ID: 35033e47-38f6-4912-b14d-e23b5c7390d7</para>
        /// </summary>
        [SitecoreField("Menu Items")]
        public virtual IEnumerable<Guid> MenuItems {get; set;}
        public const string MenuItemsFieldId = "35033e47-38f6-4912-b14d-e23b5c7390d7";
        public const string MenuItemsFieldName = "Menu Items";

    }


    /// <summary>
    /// IMenuItem Interface
    /// <para>Path: /sitecore/templates/Wooli/Feature/Navigation/Menu Item</para>
    /// <para>ID: 5dccb05c-59f3-4579-aea3-6e5dc934c7b0</para>
    /// </summary>
    [SitecoreType(TemplateId="5dccb05c-59f3-4579-aea3-6e5dc934c7b0")]
    public partial interface IMenuItem: IGlassBase
    {

        /// <summary>
        /// The Commerce Categories field.
        /// <para>Field Type: Treelist</para>
        /// <para>Field ID: 1059d1e9-7ee8-4021-9a18-b7876ff11e28</para>
        /// </summary>
        [SitecoreField("Commerce Categories")]
        IEnumerable<Guid> CommerceCategories {get; set;}

        /// <summary>
        /// The Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: 8d6d3e24-814b-4c4a-b0d8-c2f9d607b923</para>
        /// </summary>
        [SitecoreField("Image")]
        Image Image {get; set;}

        /// <summary>
        /// The Title field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 2f131184-e443-4376-94b3-2283d246d205</para>
        /// </summary>
        [SitecoreField("Title")]
        string Title {get; set;}

    }


    /// <summary>
    /// MenuItem Class
    /// <para>Path: /sitecore/templates/Wooli/Feature/Navigation/Menu Item</para>
    /// <para>ID: 5dccb05c-59f3-4579-aea3-6e5dc934c7b0</para>
    /// </summary>
    [SitecoreType(TemplateId="5dccb05c-59f3-4579-aea3-6e5dc934c7b0")]
    public partial class MenuItem: GlassBase, IMenuItem
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/Wooli/Feature/Navigation/Menu Item
        /// </summary>
        public const string TemplateId = "5dccb05c-59f3-4579-aea3-6e5dc934c7b0";

        /// <summary>
        /// The Commerce Categories field.
        /// <para>Field Type: Treelist</para>
        /// <para>Field ID: 1059d1e9-7ee8-4021-9a18-b7876ff11e28</para>
        /// </summary>
        [SitecoreField("Commerce Categories")]
        public virtual IEnumerable<Guid> CommerceCategories {get; set;}
        public const string CommerceCategoriesFieldId = "1059d1e9-7ee8-4021-9a18-b7876ff11e28";
        public const string CommerceCategoriesFieldName = "Commerce Categories";

        /// <summary>
        /// The Image field.
        /// <para>Field Type: Image</para>
        /// <para>Field ID: 8d6d3e24-814b-4c4a-b0d8-c2f9d607b923</para>
        /// </summary>
        [SitecoreField("Image")]
        public virtual Image Image {get; set;}
        public const string ImageFieldId = "8d6d3e24-814b-4c4a-b0d8-c2f9d607b923";
        public const string ImageFieldName = "Image";

        /// <summary>
        /// The Title field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 2f131184-e443-4376-94b3-2283d246d205</para>
        /// </summary>
        [SitecoreField("Title")]
        public virtual string Title {get; set;}
        public const string TitleFieldId = "2f131184-e443-4376-94b3-2283d246d205";
        public const string TitleFieldName = "Title";

    }


    /// <summary>
    /// IMenuItemFolder Interface
    /// <para>Path: /sitecore/templates/Wooli/Feature/Navigation/Menu Item Folder</para>
    /// <para>ID: b1142e79-d313-41b1-b3c2-268ebb80c489</para>
    /// </summary>
    [SitecoreType(TemplateId="b1142e79-d313-41b1-b3c2-268ebb80c489")]
    public partial interface IMenuItemFolder: IGlassBase
    {

    }


    /// <summary>
    /// MenuItemFolder Class
    /// <para>Path: /sitecore/templates/Wooli/Feature/Navigation/Menu Item Folder</para>
    /// <para>ID: b1142e79-d313-41b1-b3c2-268ebb80c489</para>
    /// </summary>
    [SitecoreType(TemplateId="b1142e79-d313-41b1-b3c2-268ebb80c489")]
    public partial class MenuItemFolder: GlassBase, IMenuItemFolder
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/Wooli/Feature/Navigation/Menu Item Folder
        /// </summary>
        public const string TemplateId = "b1142e79-d313-41b1-b3c2-268ebb80c489";

    }

}