# Build using Visual Studio 2017 on Windows Server 2016.
# Variables with password stored in Azure secrets

trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  build_cake: "./src/build.cake"
  artifacts_location: "$(Pipeline.Workspace)/s/output"

steps:

- task: UseNode@1
  displayName: Install Node 16
  inputs:
    version: '16.x'

- task: DownloadPipelineArtifact@2
  displayName: Download tools
  inputs:
    buildType: 'specific'
    project: 'c8a112df-eb95-41fa-bb80-48e83128fe75'
    definition: '10'
    buildVersionToDownload: 'latest'
    artifactName: 'tools'
    targetPath: '$(Pipeline.Workspace)/s/src/tools'

- task: DownloadPipelineArtifact@2
  displayName: Download node modules
  inputs:
    buildType: 'specific'
    project: 'c8a112df-eb95-41fa-bb80-48e83128fe75'
    definition: '10'
    buildVersionToDownload: 'latest'
    artifactName: 'node_modules'
    targetPath: '$(Pipeline.Workspace)/s/src/node_modules'

- task: DownloadPipelineArtifact@2
  displayName: Download client node modules
  inputs:
    buildType: 'specific'
    project: 'c8a112df-eb95-41fa-bb80-48e83128fe75'
    definition: '10'
    buildVersionToDownload: 'latest'
    artifactName: 'client_node_modules'
    targetPath: '$(Pipeline.Workspace)/s/src/client/node_modules'

- task: DownloadSecureFile@1
  displayName: Download license
  name: license_file
  inputs:
    secureFile: 'license.xml'

- task: DownloadPipelineArtifact@2
  displayName: Download NuGet packages
  inputs:
    buildType: 'specific'
    project: 'c8a112df-eb95-41fa-bb80-48e83128fe75'
    definition: '10'
    buildVersionToDownload: 'latest'
    artifactName: 'packages'
    targetPath: '$(Pipeline.Workspace)/s/src/packages'

- task: PowerShell@2
  displayName: Move license_file
  inputs:
    targetType: 'inline'
    script: |
      move $(license_file.secureFilePath) ./src/ -Force

- task: DotNetCoreCLI@2
  displayName: Add sitecore nuget source
  inputs:
    command: 'custom'
    custom: 'nuget'
    arguments: 'add source -n Sitecore https://sitecore.myget.org/F/sc-packages/api/v3/index.json'
    workingDirectory: '$(Pipeline.Workspace)/s'

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: 'Connect.DynamicsRetail Nuget connection'

- task: DotNetCoreCLI@2
  displayName: Restore .Net Core tools
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'restore'
    workingDirectory: './'

- task: Cake@2
  displayName: "NuGet restore"
  inputs:
    script: 'src/build.cake'
    target: 'Restore :: Restore NuGet Packages'
    verbosity: 'Quiet'
    Version: '1.3.0'

- task: Cake@2
  displayName: Build Server Code
  inputs:
    script: 'src/build.cake'
    target: '008-Build-Server-Code'
    verbosity: 'Quiet'
    Version: '1.3.0'

- task: Cake@2
  displayName: Run Unit tests
  inputs:
    script: 'src/build.cake'
    target: '003-Tests'
    verbosity: 'Quiet'
    Version: '1.3.0'


- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Pipeline.Workspace)/s/output/tests/coverage/cobertura-coverage.xml'
