---
ID: "19f5d691-2fe0-45a6-a641-a5b123c66161"
Parent: "a5d2a17d-9104-434b-8b19-c77c09f0e796"
Template: "5c547d4e-7111-4995-95b0-6b561751bf2e"
Path: "/sitecore/layout/Placeholder Settings/HCA/Feature/Catalog/product-properties"
SharedFields:
- ID: "7256bdab-1fd2-49dd-b205-cb4873d2917c"
  Hint: Placeholder Key
  Value: "product-properties"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180504T122228Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1e9feab6-6c14-437d-affa-0b2b90956b3a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210122T150013Z
