---
ID: "9bbcb98e-ec75-47d4-abc1-f1bd20279cce"
Parent: "a5d2a17d-9104-434b-8b19-c77c09f0e796"
Template: "5c547d4e-7111-4995-95b0-6b561751bf2e"
Path: "/sitecore/layout/Placeholder Settings/HCA/Feature/Catalog/product-filters"
DB: master
SharedFields:
- ID: "7256bdab-1fd2-49dd-b205-cb4873d2917c"
  Hint: Placeholder Key
  Value: "product-filters"
- ID: "e391b526-d0c5-439d-803e-17512eae6222"
  Hint: Allowed Controls
  Type: TreelistEx
  Value: "{1C8D57C1-E884-48CC-9E45-E8472F07BD09}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210129T142110Z
