---
ID: "134a0e28-8517-484c-9ff8-077a7a2cdbb0"
Parent: "ff3f660a-3d15-4efc-9873-113aaf71b44e"
Template: "ff3f660a-3d15-4efc-9873-113aaf71b44e"
Path: /sitecore/templates/HCA/Project/HCA/Folders/Settings Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200522T090347Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1ebe167d-77ac-4433-8661-a2d029720820"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210122T150051Z
