---
ID: "45c057b5-749b-4149-a1de-8542df348e98"
Parent: "656950e2-cdb1-4899-8106-067a6b76468b"
Template: "656950e2-cdb1-4899-8106-067a6b76468b"
Path: /sitecore/templates/HCA/Feature/Navigation/Footer/Social Network Link/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200428T184856Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
