---
ID: "45c057b5-749b-4149-a1de-8542df348e98"
Parent: "656950e2-cdb1-4899-8106-067a6b76468b"
Template: "656950e2-cdb1-4899-8106-067a6b76468b"
Path: /sitecore/templates/HCA/Feature/Navigation/Social Network Links/Social Network Link/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200428T184856Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9294d8d3-b652-4d0b-81a6-5db70d4ca158"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210122T150026Z
