---
ID: "6eb0dbdd-04b6-4d34-acc7-e1476bc67580"
Parent: "2c9c975e-89d7-4c96-bf7b-74ac622d54ab"
Template: "2c9c975e-89d7-4c96-bf7b-74ac622d54ab"
Path: /sitecore/templates/HCA/Feature/Navigation/Footer/Footer Link/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200428T185028Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
