---
ID: "481fae61-53eb-4141-9879-4588bd5765e9"
Parent: "5dd201a0-5b3d-4e82-8cca-608d5905c3a1"
Template: "5dd201a0-5b3d-4e82-8cca-608d5905c3a1"
Path: /sitecore/templates/CommerceConnect/Sitecore Commerce/Commerce Control Panel/Commerce Engine Settings/Commerce Term/Commerce Term/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150825T143733Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1361833e-a363-4acb-ae76-0fcb66958ab7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20161202T134018Z
